spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/access-management
    username: postgres
    password: root
  application:
    name: ACCESS-MANAGEMENT
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: master
    loadbalancer:
      ribbon:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/am-realm
server:
  port: 65025
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8777/eureka/
keycloak:
  realm: am-realm
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: access-management
  credentials:
    secret: zRBzHE8tLRvcHakGHsqHwcacxFYldYFf

mail-service-url: http://MAIL-SERVICE/mails
