spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/company-management
    username: postgres
    password: root
  application:
    name: ACCESS-MANAGEMENT
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/
jwt:
  hoursToExpire: 1