spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/access-management
    username: postgres
    password: root
  application:
    name: ACCESS-MANAGEMENT
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 65025
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/
jwt:
  hoursToExpire: 1
keycloak:
  realm: am-realm
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: access-management
  credentials:
    secret: gkPAebLYwgQMIDrLX5uJc324R8KU4ZOt